"""Add sad

Revision ID: d71ca70c82e3
Revises: eb6df99533f4
Create Date: 2024-09-12 13:04:50.798997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71ca70c82e3'
down_revision: Union[str, None] = 'eb6df99533f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('test', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'test')
    # ### end Alembic commands ###
